### ISSUE TITLE
Optimize on resize/crop (variations) doesn't function

### ISSUE THREAD

**Issue by iangregory** [matjazpotocnik/AutoSmush#2]
I have AutoSmush configured only to optimize on resize/crop (variations). However, I can see from the logs that this does't work - the images are never optimized.

Having reviewed the code it appears that the hook is being added on line [1256](https://github.com/matjazpotocnik/AutoSmush/blob/f6361465c2e5c061a33c0d9cf3e2b97946ee2559/AutoSmush.module#L1256) in the `ready()` function.

However, we return earlier in that function (line [1207](https://github.com/matjazpotocnik/AutoSmush/blob/f6361465c2e5c061a33c0d9cf3e2b97946ee2559/AutoSmush.module#L1202)) if the page is not an admin page, so the hook is never added.

Commenting out line 1207 causes images to be smushed when they're resized (i.e. on first load) as expected.

**Comment by matjazpotocnik** [comment]
Hm, it's working here. Could you enable debug mode and see if the hook is applied? Also please add 

`$this->log->save($page->template->name);`

before line 1207, just to check what is the template name.

**Comment by iangregory** [comment]
Debug mode indicates the hook isn't being applied. The template name is 'home'

`2018-01-16 21:00:22     home`

**Comment by matjazpotocnik** [comment]
Hmm... How do you create variations? Could you also log $page->process?

**Comment by matjazpotocnik** [comment]
This is fixed in 1.1.4.
