### ISSUE TITLE
Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by rolandtoth** [matjazpotocnik/AutoSmush#3]
As of PHP 7.2 this error comes up on optimize. I replaced 3 occurrences of count() with wireCount() which fixed it (the excluded one was on line 581). 

https://github.com/processwire/processwire-issues/issues/408

I'm not sure this is the best solution though, I don't know if this in earlier PW versions would work or not.

**Comment by matjazpotocnik** [comment]
Hi Roland! I'm on PHP 7.2 and don't see these warnings, but I'm sure they can pop up so in the next version I'll fix this. wireCount() wouldn't work prior to PW 3.0.79 so I'll implement count in Autosmush module itself.

**Comment by matjazpotocnik** [comment]
This is fixed in 1.1.4.
